### ISSUE TITLE
Hybrid npm module for ESM and CommonJS

### ISSUE THREAD

**Issue by Morekon** [Vincent-Pang/builder-pattern#19]
Currently the project is only distributed as CommonJS module.
To also support optimized bundle size it would also make sense to distribute the project as ESM module.

I have found an article about this topic that describes how to create an hybrid that uses the same codebase to build ESM and CommonJS distributions:
https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by Vincent-Pang** [comment]
Thank you for your suggestion, it inspires me a lot. And the link you provided become my starting point for ESM.

After investigating a lot of related configurations, distributed in CommonJS and ESM formats finally come.

I publish it in v2.0.0 for safety although I expect it is compatible with v1.x.x.

It should be worked with both old NodeJS (doesn't support esm) and new NodeJS (supports both cjs and esm).
